import {
  BsFillHouseDoorFill,
  FaBed,
  FaClone,
  FaCrown,
  FaUsers,
  MdBed,
} from "@/components/icons";
import { CategoryInterface } from "@/type";

export const categories: CategoryInterface[] = [
  {
    label: "Basicas",
    units: [202, 503],
    Icon: MdBed,
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "basicas",
  },
  {
    label: "Doble Camas",
    units: [102, 402, 502],
    Icon: FaBed,
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "doble-camas",
  },
  {
    label: "Executivas",
    units: [201, 301, 204, 401],
    Icon: FaCrown,
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "ejecutivas",
  },
  {
    label: "Standars",
    units: [203, 501],
    Icon: BsFillHouseDoorFill,
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "standars",
  },
  {
    label: "Dobles",
    units: [403, 504],
    Icon: FaClone,
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "dobles",
  },
  {
    label: "Familiares",
    Icon: FaUsers,
    units: [302],
    maxGuestsPerUnit: 4,
    totalUnits: 2,
    bgImage: "/assets/images/home/header/HQNRD-first-featured-image.webp",
    btnCTA: "View Rooms",
    slug: "familiares",
  },
  {
    label: "Ver Todas",
    Icon: FaUsers,
    units: [],
    maxGuestsPerUnit: 0,
    totalUnits: 0,
    bgImage: "",
    btnCTA: "",
    slug: "",
  },
];
