import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Providers from "@/providers";
import { ModeToggle } from "@/components/features/ThemeToggle";
import { LanguageDialogPicker } from "@/components/features/LocaleModalDialog";
import { i18n, Locale } from "@/i18n-config";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface LayoutProps {
  children: ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ModeToggle />
          <LanguageDialogPicker lang={lang} btnVariant="outline" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
