import { ScrollArea } from "@/components/ui/scroll-area";
import { i18n, Locale } from "@/i18n-config";
import Providers from "@/providers";
import "@/styles/globals.css";
import { poppins } from "@/utils/fonts";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface LayoutProps {
  children: ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <html
      lang={lang}
      suppressHydrationWarning
      className={`scroll-smooth focus:scroll-auto ${poppins.className}`}
    >
      <body className={`${poppins.className} subpixel-antialiased`}>
        <ScrollArea className="h-screen w-full">
          <Providers>{children}</Providers>
        </ScrollArea>
      </body>
    </html>
  );
}
